apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: LoadBalancer
  selector:
    app: mywebapp
  ports:
      - port: 8081
      # protocol: TCP
        targetPort: 8081
        #nodePort: 30001     