apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: NodePort
  selector:
    app: mywebapp
  ports:
      - port: 8082
      # protocol: TCP
        #targetPort: 8082
        #nodePort: 30001     