apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebapp
spec:
  selector:
    matchLabels:
      app: mywebapp
  template:
    metadata:
      labels:
        app: mywebapp
    spec:
      containers:
        - name: mywebapp
          image: aartibh/javakubernetes-poc:version3
          #image: punitg237/springboot-mysql:springboot-app
          imagePullPolicy: Always
          ports:
            - containerPort: 8081 
          env:
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
            # - name: SPRING_DATASOURCE_URL
            #   value: jdbc:mysql://mysqldb/store_db

    